### PR TITLE
add debian/ build for libucl

### PR DESCRIPTION
**Pull request by igalic**
This should enable (outside contributors) to easily build their own .deb
packages of this repository, or automate that process thru Launchpad's
PPA service.

This first commit is autogenerated thru `dh_make`.

### CODE REVIEW

**Comment by igalic** [comment]
n.b.: `fakeroot debian/rules` is currently failing due to `make test` failing on 

```
========================================
   libucl 0.8.0: tests/test-suite.log
========================================

# TOTAL: 6
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: schema
============

rm: cannot remove '/tmp/_ucl_test_schema.out': No such file or directory
running schema test suite additionalItems.json... OK
running schema test suite additionalProperties.json... OK
running schema test suite allOf.json... OK
running schema test suite anyOf.json... OK
running schema test suite definitions.json... Fail
running schema test suite dependencies.json... OK
running schema test suite enum.json... OK
running schema test suite items.json... OK
running schema test suite maxItems.json... OK
running schema test suite maxLength.json... OK
running schema test suite maxProperties.json... OK
running schema test suite maximum.json... OK
running schema test suite minItems.json... OK
running schema test suite minLength.json... OK
running schema test suite minProperties.json... OK
running schema test suite minimum.json... OK
running schema test suite multipleOf.json... OK
running schema test suite not.json... OK
running schema test suite oneOf.json... OK
running schema test suite pattern.json... OK
running schema test suite patternProperties.json... OK
running schema test suite properties.json... OK
running schema test suite ref.json... Fail
running schema test suite refRemote.json... Fail
running schema test suite required.json... OK
running schema test suite type.json... OK
running schema test suite uniqueItems.json... OK
FAIL schema.test (exit status: 1)
```

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by igalic** [comment]
Well, yeah, since this PR, i've moved house, had a child, became self-employed in germany and am now a stay-at-home mom because my DevOps job is non-essential (either that, or customers in Germany *really* like to have people on-site)

We've also moved _real_ testing over to [CirrusCI](https://cirrus-ci.com/github/bsdci/libioc), and it's failing for very interesting reasons in py-libzfs: https://github.com/bsdci/libioc/pull/753#issuecomment-612628330

**Comment by igalic** [comment]
there's a libucl(-dev) package there's a Debian package, so let's close this.

**Comment by samatjain** [comment]
Annoyingly, Debian still does not have _this_ libucl. The [libucl package that is in Debian](https://packages.debian.org/search?suite=sid&section=all&arch=any&searchon=names&keywords=libucl) is for an unrelated compression library.

Could we re-open this MR?

**Pull request closed without merging**
